# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import async_pb2 as async__pb2


class async_SGDStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send_Weights = channel.unary_unary(
        '/stochastic.async_SGD/Send_Weights',
        request_serializer=async__pb2.WS_Update.SerializeToString,
        response_deserializer=async__pb2.ACK.FromString,
        )


class async_SGDServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Send_Weights(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_async_SGDServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send_Weights': grpc.unary_unary_rpc_method_handler(
          servicer.Send_Weights,
          request_deserializer=async__pb2.WS_Update.FromString,
          response_serializer=async__pb2.ACK.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stochastic.async_SGD', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
