# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: async.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='async.proto',
  package='stochastic',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61sync.proto\x12\nstochastic\"e\n\tWS_Update\x12,\n\x04w_up\x18\x01 \x03(\x0b\x32\x1e.stochastic.WS_Update.WUpEntry\x1a*\n\x08WUpEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x12\n\x03\x41\x43K\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32\x43\n\tasync_SGD\x12\x36\n\x0cSend_Weights\x12\x15.stochastic.WS_Update\x1a\x0f.stochastic.ACKb\x06proto3')
)




_WS_UPDATE_WUPENTRY = _descriptor.Descriptor(
  name='WUpEntry',
  full_name='stochastic.WS_Update.WUpEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='stochastic.WS_Update.WUpEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='stochastic.WS_Update.WUpEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=128,
)

_WS_UPDATE = _descriptor.Descriptor(
  name='WS_Update',
  full_name='stochastic.WS_Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w_up', full_name='stochastic.WS_Update.w_up', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_WS_UPDATE_WUPENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=128,
)


_ACK = _descriptor.Descriptor(
  name='ACK',
  full_name='stochastic.ACK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='stochastic.ACK.ack', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=148,
)

_WS_UPDATE_WUPENTRY.containing_type = _WS_UPDATE
_WS_UPDATE.fields_by_name['w_up'].message_type = _WS_UPDATE_WUPENTRY
DESCRIPTOR.message_types_by_name['WS_Update'] = _WS_UPDATE
DESCRIPTOR.message_types_by_name['ACK'] = _ACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WS_Update = _reflection.GeneratedProtocolMessageType('WS_Update', (_message.Message,), dict(

  WUpEntry = _reflection.GeneratedProtocolMessageType('WUpEntry', (_message.Message,), dict(
    DESCRIPTOR = _WS_UPDATE_WUPENTRY,
    __module__ = 'async_pb2'
    # @@protoc_insertion_point(class_scope:stochastic.WS_Update.WUpEntry)
    ))
  ,
  DESCRIPTOR = _WS_UPDATE,
  __module__ = 'async_pb2'
  # @@protoc_insertion_point(class_scope:stochastic.WS_Update)
  ))
_sym_db.RegisterMessage(WS_Update)
_sym_db.RegisterMessage(WS_Update.WUpEntry)

ACK = _reflection.GeneratedProtocolMessageType('ACK', (_message.Message,), dict(
  DESCRIPTOR = _ACK,
  __module__ = 'async_pb2'
  # @@protoc_insertion_point(class_scope:stochastic.ACK)
  ))
_sym_db.RegisterMessage(ACK)


_WS_UPDATE_WUPENTRY.has_options = True
_WS_UPDATE_WUPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_ASYNC_SGD = _descriptor.ServiceDescriptor(
  name='async_SGD',
  full_name='stochastic.async_SGD',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=150,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send_Weights',
    full_name='stochastic.async_SGD.Send_Weights',
    index=0,
    containing_service=None,
    input_type=_WS_UPDATE,
    output_type=_ACK,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASYNC_SGD)

DESCRIPTOR.services_by_name['async_SGD'] = _ASYNC_SGD

# @@protoc_insertion_point(module_scope)
