apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: systems
  labels:
    name: systems
spec:
  serviceName: "systems-service"
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: henrydeclety/worker
          command:
            - sleep
            - infinity
          imagePullPolicy: Always
          ports:
          - containerPort: 50051
            name: web
          volumeMounts:
          - name: data
            mountPath: /worker/datasets
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: cs449g3-scratch
